# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hinge < Formula
  desc ""
  homepage "https://github.com/pacoguzman/hinge"
  version "2.0.2"

  on_macos do
    url "https://github.com/pacoguzman/hinge/releases/download/v2.0.2/hinge_2.0.2_darwin_all.tar.gz"
    sha256 "20fa4a3541acfd16c6ed4d433d6694753fb10e7d38270d95dd2a88c50ab7e985"

    def install
      bin.install "hinge"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pacoguzman/hinge/releases/download/v2.0.2/hinge_2.0.2_linux_arm64.tar.gz"
      sha256 "c53266fbffd28f25be9f43c53a53dbe20f277190be2de127d049186f7d6ab130"

      def install
        bin.install "hinge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pacoguzman/hinge/releases/download/v2.0.2/hinge_2.0.2_linux_amd64.tar.gz"
      sha256 "fe40232f1282dd192816825eb504aa728ffad0b487933fb8da4f7e9d49746076"

      def install
        bin.install "hinge"
      end
    end
  end
end
