# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hinge < Formula
  desc ""
  homepage "https://github.com/pacoguzman/hinge"
  version "2.0.0"

  on_macos do
    url "https://github.com/pacoguzman/hinge/releases/download/v2.0.0/hinge_2.0.0_darwin_all.tar.gz"
    sha256 "e4912f18365f33b054dce3d48b3d4a7e960a07580056da4f8b9db33f71b12c19"

    def install
      bin.install "hinge"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pacoguzman/hinge/releases/download/v2.0.0/hinge_2.0.0_linux_arm64.tar.gz"
      sha256 "2640cccd681e404e99fc9765aea3e16861e44fa4060d1f6f6963646c51842de0"

      def install
        bin.install "hinge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pacoguzman/hinge/releases/download/v2.0.0/hinge_2.0.0_linux_amd64.tar.gz"
      sha256 "12e0de5b67a8cb1741ffc6f42e16635f035d5e052e48d64c9e70ab9904d1d772"

      def install
        bin.install "hinge"
      end
    end
  end
end
